version: "2"
services:
  proxy:
    #image: micahhausler/es-proxy
    build: ./
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: "<>"
      AWS_SECRET_ACCESS_KEY: "<>"
      AWS_REGION: "us-west-2"
      ES_DOMAIN: ""
      LOG_LEVEL: "INFO"
  kibana:
    image: "kibana:4.5.4"
    entrypoint: kibana
    command: "-c /etc/kibana/kibana.yaml"
    volumes:
      - "./kibana-config.yaml:/etc/kibana/kibana.yaml"
    ports:
      - "5601:5601"
    links:
      - proxy
