port: 5601
host: "0.0.0.0"
elasticsearch_url: "http://proxy:8080"
elasticsearch_preserve_host: true
kibana_index: ".kibana-4"
default_app_id: "discover"
request_timeout: 20000
verify_ssl: true
logging.verbose: false
bundled_plugin_ids:
 - plugins/dashboard/index
 - plugins/discover/index
 - plugins/doc/index
 - plugins/kibana/index
 - plugins/markdown_vis/index
 - plugins/metric_vis/index
 - plugins/settings/index
 - plugins/table_vis/index
 - plugins/vis_types/index
 - plugins/visualize/index
